'use strict';
const xml = require('./xml');
const { DocMap } = require('./docmap');
const { Paragraphs } = require('./paragraphs');
const { Comments } = require('./comments');
const { Formatting } = require('./formatting');
const { Footnotes } = require('./footnotes');

class ParagraphHandle {
  constructor(engine, paraId) { this._engine = engine; this._paraId = paraId; }
  get id() { return this._paraId; }
  get text() { return xml.extractTextDecoded(this._locate().xml); }
  get type() { var loc = this._locate(); var l = Paragraphs._headingLevel(loc.xml); if (l > 0) return 'heading'; var t = xml.extractTextDecoded(loc.xml).trim(); if (/^(Figure|Table)\s+\d/i.test(t)) return 'caption'; if (/^abstract$/i.test(t)) return 'abstract'; return 'body'; }
  get section() { var ws = this._getWorkspace(); var pp = xml.findParagraphs(ws.docXml); var loc = this._locate(); var mi = -1; for (var i = 0; i < pp.length; i++) { if (pp[i].start === loc.start) { mi = i; break; } } if (mi === -1) return '(unknown)'; for (var j = mi - 1; j >= 0; j--) { if (Paragraphs._headingLevel(pp[j].xml) > 0) return xml.extractTextDecoded(pp[j].xml); } return '(before first heading)'; }
  replace(oldText, newText, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var tracked = opts.tracked !== undefined ? opts.tracked : this._engine._tracked; var author = opts.author || this._engine._author; if (tracked) { var nextId = xml.nextChangeId(ws.docXml); var result = Paragraphs._injectReplacement(loc.xml, oldText, newText, nextId, author, this._engine._date); if (result.modified) { ws.docXml = ws.docXml.slice(0, loc.start) + result.xml + ws.docXml.slice(loc.end); } else { throw new Error('Text not found in paragraph ' + this._paraId); } } else { var proxy = { _xml: loc.xml, get docXml() { return this._xml; }, set docXml(v) { this._xml = v; } }; if (!xml.extractTextDecoded(loc.xml).includes(oldText)) throw new Error('Text not found in paragraph ' + this._paraId); Paragraphs._replaceDirect(proxy, oldText, newText); ws.docXml = ws.docXml.slice(0, loc.start) + proxy.docXml + ws.docXml.slice(loc.end); } return this; }
  delete(text, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var tracked = opts.tracked !== undefined ? opts.tracked : this._engine._tracked; if (tracked) { var nextId = xml.nextChangeId(ws.docXml); var result = Paragraphs._injectDeletion(loc.xml, text, nextId, opts.author || this._engine._author, this._engine._date); if (result.modified) ws.docXml = ws.docXml.slice(0, loc.start) + result.xml + ws.docXml.slice(loc.end); else throw new Error('Text not found'); } else { this.replace(text, '', { tracked: false }); } return this; }
  bold(text, opts) { if (!opts) opts = {}; this._fmtP('bold', text, opts); return this; }
  italic(text, opts) { if (!opts) opts = {}; this._fmtP('italic', text, opts); return this; }
  highlight(text, color, opts) { if (!opts) opts = {}; if (typeof color === 'object') { opts = color; color = 'yellow'; } this._fmtP('highlight', text, Object.assign({}, opts, { colorName: color || 'yellow' })); return this; }
  comment(text, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var pt = xml.extractTextDecoded(loc.xml); var a = pt.slice(0, 80); if (!a) throw new Error('No text'); Comments.add(ws, a, text, { author: opts.by || opts.author || this._engine._author, initials: opts.initials || (opts.by || opts.author || this._engine._author).split(' ').map(function(w){return w[0];}).join(''), date: this._engine._date }); return this; }
  footnote(text, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); Footnotes.add(ws, xml.extractTextDecoded(loc.xml).slice(0, 80), text, { author: opts.author || this._engine._author, date: this._engine._date }); return this; }
  getXml() { return this._locate().xml; }
  setXml(xmlString) { var ws = this._getWorkspace(); var loc = this._locate(); ws.docXml = ws.docXml.slice(0, loc.start) + xmlString + ws.docXml.slice(loc.end); return this; }
  injectXml(xmlString, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var paraXml = loc.xml; var at = opts.before || opts.after; if (!at) throw new Error('Need before or after'); var dec = xml.extractTextDecoded(paraXml); var ai = dec.indexOf(at); if (ai === -1) throw new Error('Text not found'); var to = opts.before ? ai : ai + at.length; var runs = xml.parseRuns(paraXml); var cc = 0; for (var ri = 0; ri < runs.length; ri++) { var r = runs[ri]; if (r.texts.length === 0) continue; var rt = r.combinedText; var re = cc + rt.length; if (to >= cc && to <= re) { var oir = to - cc; if (oir === 0) { paraXml = paraXml.slice(0, r.index) + xmlString + paraXml.slice(r.index); } else if (oir === rt.length) { var ap = r.index + r.fullMatch.length; paraXml = paraXml.slice(0, ap) + xmlString + paraXml.slice(ap); } else { var b = rt.slice(0, oir); var a = rt.slice(oir); var sx = '<w:r>' + r.rPr + '<w:t xml:space="preserve">' + b + '</w:t></w:r>' + xmlString + '<w:r>' + r.rPr + '<w:t xml:space="preserve">' + a + '</w:t></w:r>'; paraXml = paraXml.slice(0, r.index) + sx + paraXml.slice(r.index + r.fullMatch.length); } break; } cc += rt.length; } ws.docXml = ws.docXml.slice(0, loc.start) + paraXml + ws.docXml.slice(loc.end); return this; }
  runs() { var loc = this._locate(); var rr = xml.parseRuns(loc.xml); var res = []; for (var i = 0; i < rr.length; i++) { var r = rr[i]; if (r.texts.length === 0) continue; var tm = r.fullMatch.match(/w14:textId="([^"]+)"/); res.push({ textId: tm ? tm[1] : null, text: xml.decodeXml(r.combinedText), formatting: RunHandle._parseFormatting(r.rPr) }); } return res; }
  mergeRuns() { var ws = this._getWorkspace(); var loc = this._locate(); var px = loc.xml; var rr = xml.parseRuns(px); var tr = rr.filter(function(r){return r.texts.length > 0;}); if (tr.length < 2) return 0; var m = 0; for (var i = tr.length - 1; i > 0; i--) { var c = tr[i]; var p = tr[i-1]; if (c.rPr.replace(/\s+/g,' ').trim() === p.rPr.replace(/\s+/g,' ').trim()) { var ct = p.combinedText + c.combinedText; var nr = '<w:r>' + p.rPr + '<w:t xml:space="preserve">' + ct + '</w:t></w:r>'; px = px.slice(0, c.index) + px.slice(c.index + c.fullMatch.length); px = px.slice(0, p.index) + nr + px.slice(p.index + p.fullMatch.length); m++; } } if (m > 0) ws.docXml = ws.docXml.slice(0, loc.start) + px + ws.docXml.slice(loc.end); return m; }
  replaceAt(start, end, newText, opts) { if (!opts) opts = {}; var ft = xml.extractTextDecoded(this._locate().xml); if (start < 0 || end > ft.length || start >= end) throw new Error('Invalid offsets'); return this.replace(ft.slice(start, end), newText, opts); }
  run(textId) { return new RunHandle(this._engine, this._paraId, textId); }
  insertAfter(text, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var tracked = opts.tracked !== undefined ? opts.tracked : this._engine._tracked; var pPr = Paragraphs._extractPpr(loc.xml); var npi = xml.randomHexId().toUpperCase(); var nti = xml.randomHexId().toUpperCase(); var et = xml.escapeXml(text); var rp = '<w:rPr><w:rFonts w:hint="default" w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman" w:cs="Times New Roman" /><w:sz w:val="24" /></w:rPr>'; var np; if (tracked) { var id = xml.nextChangeId(ws.docXml); np = '<w:p w14:paraId="' + npi + '" w14:textId="' + nti + '">' + pPr + '<w:ins w:id="' + id + '" w:author="' + xml.escapeXml(opts.author || this._engine._author) + '" w:date="' + this._engine._date + '"><w:r>' + rp + '<w:t xml:space="preserve">' + et + '</w:t></w:r></w:ins></w:p>'; } else { np = '<w:p w14:paraId="' + npi + '" w14:textId="' + nti + '">' + pPr + '<w:r>' + rp + '<w:t xml:space="preserve">' + et + '</w:t></w:r></w:p>'; } ws.docXml = ws.docXml.slice(0, loc.end) + np + ws.docXml.slice(loc.end); return npi; }
  insertBefore(text, opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var tracked = opts.tracked !== undefined ? opts.tracked : this._engine._tracked; var pPr = Paragraphs._extractPpr(loc.xml); var npi = xml.randomHexId().toUpperCase(); var nti = xml.randomHexId().toUpperCase(); var et = xml.escapeXml(text); var rp = '<w:rPr><w:rFonts w:hint="default" w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman" w:cs="Times New Roman" /><w:sz w:val="24" /></w:rPr>'; var np; if (tracked) { var id = xml.nextChangeId(ws.docXml); np = '<w:p w14:paraId="' + npi + '" w14:textId="' + nti + '">' + pPr + '<w:ins w:id="' + id + '" w:author="' + xml.escapeXml(opts.author || this._engine._author) + '" w:date="' + this._engine._date + '"><w:r>' + rp + '<w:t xml:space="preserve">' + et + '</w:t></w:r></w:ins></w:p>'; } else { np = '<w:p w14:paraId="' + npi + '" w14:textId="' + nti + '">' + pPr + '<w:r>' + rp + '<w:t xml:space="preserve">' + et + '</w:t></w:r></w:p>'; } ws.docXml = ws.docXml.slice(0, loc.start) + np + ws.docXml.slice(loc.start); return npi; }
  remove(opts) { if (!opts) opts = {}; var ws = this._getWorkspace(); var loc = this._locate(); var tracked = opts.tracked !== undefined ? opts.tracked : this._engine._tracked; if (tracked) { var t = xml.extractTextDecoded(loc.xml); if (t.trim()) { var r = Paragraphs._injectDeletion(loc.xml, t, xml.nextChangeId(ws.docXml), opts.author || this._engine._author, this._engine._date); if (r.modified) ws.docXml = ws.docXml.slice(0, loc.start) + r.xml + ws.docXml.slice(loc.end); } } else { ws.docXml = ws.docXml.slice(0, loc.start) + ws.docXml.slice(loc.end); } }
  _locate() { var ws = this._getWorkspace(); var r = DocMap.locateById(ws.docXml, this._paraId); if (!r) throw new Error('Paragraph "' + this._paraId + '" not found'); return r; }
  _getWorkspace() { if (!this._engine._workspace) throw new Error('Document not opened yet.'); return this._engine._workspace; }
  _fmtP(ft, text, opts) { var ws = this._getWorkspace(); var loc = this._locate(); if (!xml.extractTextDecoded(loc.xml).includes(text)) throw new Error('Text not found'); var proxy = { _xml: loc.xml, get docXml() { return this._xml; }, set docXml(v) { this._xml = v; } }; var fo = { tracked: opts.tracked !== undefined ? opts.tracked : false, author: opts.author || this._engine._author, date: this._engine._date }; switch (ft) { case 'bold': Formatting.bold(proxy, text, fo); break; case 'italic': Formatting.italic(proxy, text, fo); break; case 'highlight': Formatting.highlight(proxy, text, opts.colorName || 'yellow', fo); break; } ws.docXml = ws.docXml.slice(0, loc.start) + proxy.docXml + ws.docXml.slice(loc.end); }
}

class RunHandle {
  constructor(engine, paraId, textId) { this._engine = engine; this._paraId = paraId; this._textId = textId; }
  bold(opts) { if (!opts) opts = {}; this._mrp('<w:b/>', opts); return this; }
  italic(opts) { if (!opts) opts = {}; this._mrp('<w:i/>', opts); return this; }
  text() { var rx = this._lr(); var t = []; var re = /<w:t[^>]*>([^<]*)<\/w:t>/g; var m; while ((m = re.exec(rx)) !== null) t.push(m[1]); return xml.decodeXml(t.join('')); }
  setText(nt) { return this.replace(nt); }
  formatting() { var rx = this._lr(); var m = rx.match(/<w:rPr>([\s\S]*?)<\/w:rPr>/); return RunHandle._parseFormatting(m ? m[0] : ''); }
  setFormatting(props) { var ws = this._gw(); var pl = DocMap.locateById(ws.docXml, this._paraId); if (!pl) throw new Error('Para NF'); var ss = 'w14:textId="' + this._textId + '"'; var rp = pl.xml.indexOf(ss); if (rp === -1) throw new Error('Run NF'); var rs = pl.xml.lastIndexOf('<w:r', rp); var re = pl.xml.indexOf('</w:r>', rs); if (rs === -1 || re === -1) throw new Error('Parse err'); var rx = pl.xml.slice(rs, re + 6); var ri = ''; if (props.font) ri += '<w:rFonts w:ascii="' + xml.escapeXml(props.font) + '" w:hAnsi="' + xml.escapeXml(props.font) + '"/>'; if (props.size) ri += '<w:sz w:val="' + props.size + '"/>'; if (props.bold) ri += '<w:b/>'; if (props.italic) ri += '<w:i/>'; if (props.underline) ri += '<w:u w:val="single"/>'; if (props.strike) ri += '<w:strike/>'; if (props.smallCaps) ri += '<w:smallCaps/>'; if (props.color) ri += '<w:color w:val="' + props.color.replace(/^#/,'') + '"/>'; if (props.highlight) ri += '<w:highlight w:val="' + props.highlight + '"/>'; if (props.vertAlign) ri += '<w:vertAlign w:val="' + props.vertAlign + '"/>'; var nr = ri ? '<w:rPr>' + ri + '</w:rPr>' : ''; if (rx.includes('<w:rPr>')) rx = rx.replace(/<w:rPr>[\s\S]*?<\/w:rPr>/, nr); else if (nr) { var ca = rx.indexOf('>'); rx = rx.slice(0, ca + 1) + nr + rx.slice(ca + 1); } var np = pl.xml.slice(0, rs) + rx + pl.xml.slice(re + 6); ws.docXml = ws.docXml.slice(0, pl.start) + np + ws.docXml.slice(pl.end); return this; }
  splitAt(co) { var ws = this._gw(); var pl = DocMap.locateById(ws.docXml, this._paraId); if (!pl) throw new Error('Para NF'); var ss = 'w14:textId="' + this._textId + '"'; var rp = pl.xml.indexOf(ss); if (rp === -1) throw new Error('Run NF'); var rs = pl.xml.lastIndexOf('<w:r', rp); var re = pl.xml.indexOf('</w:r>', rs); if (rs === -1 || re === -1) throw new Error('Parse'); var rx = pl.xml.slice(rs, re + 6); var t = []; var tre = /<w:t[^>]*>([^<]*)<\/w:t>/g; var tm; while ((tm = tre.exec(rx)) !== null) t.push(tm[1]); var ft = t.join(''); if (co <= 0 || co >= ft.length) throw new Error('Offset OOB'); var pm = rx.match(/<w:rPr>[\s\S]*?<\/w:rPr>/); var rPr = pm ? pm[0] : ''; var t1 = xml.randomHexId().toUpperCase(); var t2 = xml.randomHexId().toUpperCase(); var r1 = '<w:r w14:textId="' + t1 + '">' + rPr + '<w:t xml:space="preserve">' + ft.slice(0, co) + '</w:t></w:r>'; var r2 = '<w:r w14:textId="' + t2 + '">' + rPr + '<w:t xml:space="preserve">' + ft.slice(co) + '</w:t></w:r>'; var np = pl.xml.slice(0, rs) + r1 + r2 + pl.xml.slice(re + 6); ws.docXml = ws.docXml.slice(0, pl.start) + np + ws.docXml.slice(pl.end); return [t1, t2]; }
  moveTo(tpi) { var ws = this._gw(); var sp = DocMap.locateById(ws.docXml, this._paraId); if (!sp) throw new Error('Src NF'); var ss = 'w14:textId="' + this._textId + '"'; var rp = sp.xml.indexOf(ss); if (rp === -1) throw new Error('Run NF'); var rs = sp.xml.lastIndexOf('<w:r', rp); var re = sp.xml.indexOf('</w:r>', rs); if (rs === -1 || re === -1) throw new Error('Parse'); var rx = sp.xml.slice(rs, re + 6); var ns = sp.xml.slice(0, rs) + sp.xml.slice(re + 6); ws.docXml = ws.docXml.slice(0, sp.start) + ns + ws.docXml.slice(sp.end); var tp = DocMap.locateById(ws.docXml, tpi); if (!tp) throw new Error('Tgt NF'); var ci = tp.xml.lastIndexOf('</w:p>'); var nt = tp.xml.slice(0, ci) + rx + tp.xml.slice(ci); ws.docXml = ws.docXml.slice(0, tp.start) + nt + ws.docXml.slice(tp.end); this._paraId = tpi; return this; }
  replace(nt, opts) { if (!opts) opts = {}; var ws = this._gw(); var pl = DocMap.locateById(ws.docXml, this._paraId); if (!pl) throw new Error('Para NF'); var ss = 'w14:textId="' + this._textId + '"'; var rp = pl.xml.indexOf(ss); if (rp === -1) throw new Error('Run NF'); var rs = pl.xml.lastIndexOf('<w:r', rp); var re = pl.xml.indexOf('</w:r>', rs); if (rs === -1 || re === -1) throw new Error('Parse'); var rx = pl.xml.slice(rs, re + 6); var nr = rx.replace(/<w:t[^>]*>[^<]*<\/w:t>/, '<w:t xml:space="preserve">' + xml.escapeXml(nt) + '</w:t>'); var np = pl.xml.slice(0, rs) + nr + pl.xml.slice(re + 6); ws.docXml = ws.docXml.slice(0, pl.start) + np + ws.docXml.slice(pl.end); return this; }
  _gw() { if (!this._engine._workspace) throw new Error('Not opened'); return this._engine._workspace; }
  _lr() { var ws = this._gw(); var pl = DocMap.locateById(ws.docXml, this._paraId); if (!pl) throw new Error('Para NF'); var ss = 'w14:textId="' + this._textId + '"'; var rp = pl.xml.indexOf(ss); if (rp === -1) throw new Error('Run NF'); var rs = pl.xml.lastIndexOf('<w:r', rp); var re = pl.xml.indexOf('</w:r>', rs); if (rs === -1 || re === -1) throw new Error('Parse'); return pl.xml.slice(rs, re + 6); }
  static _parseFormatting(rPr) { var r = { bold: false, italic: false, underline: false, font: null, size: null, color: null, highlight: null, strike: false, vertAlign: null, smallCaps: false }; if (!rPr) return r; r.bold = /<w:b\s*\/>/.test(rPr) || /<w:b\s+/.test(rPr); r.italic = /<w:i\s*\/>/.test(rPr) || /<w:i\s+/.test(rPr); r.underline = /<w:u\s/.test(rPr); r.strike = /<w:strike/.test(rPr); r.smallCaps = /<w:smallCaps/.test(rPr); var fm = rPr.match(/w:rFonts[^>]*w:ascii="([^"]*)"/); if (fm) r.font = fm[1]; var sm = rPr.match(/<w:sz\s+w:val="(\d+)"/); if (sm) r.size = parseInt(sm[1], 10); var cm = rPr.match(/<w:color\s+w:val="([^"]*)"/); if (cm) r.color = cm[1]; var hm = rPr.match(/<w:highlight\s+w:val="([^"]*)"/); if (hm) r.highlight = hm[1]; var vm = rPr.match(/<w:vertAlign\s+w:val="([^"]*)"/); if (vm) r.vertAlign = vm[1]; return r; }
  _mrp(px, opts) { var ws = this._gw(); var pl = DocMap.locateById(ws.docXml, this._paraId); if (!pl) throw new Error('Para NF'); var ss = 'w14:textId="' + this._textId + '"'; var rp = pl.xml.indexOf(ss); if (rp === -1) throw new Error('Run NF'); var rs = pl.xml.lastIndexOf('<w:r', rp); var re = pl.xml.indexOf('</w:r>', rs); if (rs === -1 || re === -1) throw new Error('Parse'); var rx = pl.xml.slice(rs, re + 6); if (rx.includes('<w:rPr>')) rx = rx.replace('<w:rPr>', '<w:rPr>' + px); else rx = rx.replace(/>/, '><w:rPr>' + px + '</w:rPr>'); var np = pl.xml.slice(0, rs) + rx + pl.xml.slice(re + 6); ws.docXml = ws.docXml.slice(0, pl.start) + np + ws.docXml.slice(pl.end); }
}

module.exports = { ParagraphHandle, RunHandle };
